"""add billing plan and stripe fields to users

Revision ID: 0eefffb6730d
Revises: 87f897d8976a
Create Date: 2026-07-27 09:22:12.057086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eefffb6730d'
down_revision: Union[str, None] = '87f897d8976a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Hand-edited, not autogenerated: same reasoning as email_verified
    # (b1e978ad0e92) and is_admin (321e839ce910) — a plain NOT NULL
    # add_column has nothing to backfill existing rows with on Postgres.
    # server_default='free' makes every existing account free (the correct
    # default for all of them, since none of them have ever paid); dropping
    # the server_default right after means it's a one-time backfill, not
    # ongoing policy — new signups get plan='free' from the ORM model's own
    # default (models/user.py), not the database.
    op.add_column(
        'users',
        sa.Column('plan', sa.String(length=20), nullable=False, server_default=sa.text("'free'")),
    )
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('plan', server_default=None)

    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subscription_cancel_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_users_stripe_subscription_id'), 'users', ['stripe_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_column('users', 'subscription_cancel_at')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
