"""add admin flag, last login, ai request logs

Revision ID: 321e839ce910
Revises: b1e978ad0e92
Create Date: 2026-07-24 13:40:57.726557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321e839ce910'
down_revision: Union[str, None] = 'b1e978ad0e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_request_logs_created_at'), 'ai_request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_request_logs_id'), 'ai_request_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_request_logs_user_id'), 'ai_request_logs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    # Hand-edited, not autogenerated: same reasoning as email_verified in
    # b1e978ad0e92 — a plain NOT NULL add_column has nothing to backfill
    # existing rows with on Postgres. server_default=false makes every
    # existing account non-admin (the correct default for all of them);
    # dropping the server_default right after means it's a one-time
    # backfill, not ongoing policy — new signups get is_admin=False from
    # the ORM model's own default (models/user.py), not the database.
    op.add_column(
        'users',
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('is_admin', server_default=None)

    # First (and, today, only) admin: the real founder account, granted
    # directly by this migration rather than via a config/env-var mechanism
    # or a public self-serve admin-granting endpoint (that would be a
    # privilege-escalation hole). A no-op if this account doesn't exist yet
    # in a given environment (e.g. a fresh dev DB) — the UPDATE just matches
    # zero rows.
    op.execute(
        "UPDATE users SET is_admin = true WHERE email = 'brendenarcher733@gmail.com'"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_ai_request_logs_user_id'), table_name='ai_request_logs')
    op.drop_index(op.f('ix_ai_request_logs_id'), table_name='ai_request_logs')
    op.drop_index(op.f('ix_ai_request_logs_created_at'), table_name='ai_request_logs')
    op.drop_table('ai_request_logs')
    # ### end Alembic commands ###
