"""add duration_ms to ai_request_logs

Revision ID: 87f897d8976a
Revises: 321e839ce910
Create Date: 2026-07-24 14:03:31.828910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f897d8976a'
down_revision: Union[str, None] = '321e839ce910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_request_logs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_request_logs', 'duration_ms')
    # ### end Alembic commands ###
