"""add email verification, refresh tokens, action tokens

Revision ID: b1e978ad0e92
Revises: 7baa31d1bb4a
Create Date: 2026-07-20 15:52:57.014833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e978ad0e92'
down_revision: Union[str, None] = '7baa31d1bb4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_tokens_id'), 'action_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_action_tokens_token_hash'), 'action_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_action_tokens_user_id'), 'action_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Hand-edited, not autogenerated: a plain NOT NULL add_column would fail
    # outright against Postgres on a table with existing rows (no default to
    # backfill with), and even where it doesn't fail, defaulting existing
    # accounts to *unverified* would retroactively demand verification from
    # users who predate this feature entirely, for no real security benefit.
    # server_default=true backfills every existing row to verified in this
    # one migration step; dropping the server_default right after means it
    # was purely a one-time backfill, not an ongoing policy — every *new*
    # signup going forward gets email_verified=False from the ORM model's
    # own Python-level default (models/user.py), not from the database.
    op.add_column(
        'users',
        sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # Bare op.alter_column(..., server_default=None) works on Postgres but
    # SQLite has no ALTER COLUMN at all — batch mode is Alembic's portable
    # way to express this (it does the create-copy-swap dance SQLite needs
    # under the hood; on Postgres it's just a normal ALTER COLUMN).
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('email_verified', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_action_tokens_user_id'), table_name='action_tokens')
    op.drop_index(op.f('ix_action_tokens_token_hash'), table_name='action_tokens')
    op.drop_index(op.f('ix_action_tokens_id'), table_name='action_tokens')
    op.drop_table('action_tokens')
    # ### end Alembic commands ###
